---
name: LedFx Addon-dev Hue
version: 2.0.92-dev
slug: ledfx-beta-dev
description: A network based LED effect controller with support for advanced real-time audio effects!
url: https://github.com/LonelyPlayer/home-assistant-addons/tree/master/ledfx-dev
audio: true
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
auth_api: true
ingress: true
host_network: true
host_dbus: true
ingress_stream: true
ingress_port: 0
ingress_entry: "#/./"
panel_icon: mdi:emoticon-devil-outline
panel_title: LedFx-dev Hue
init: false
map:
  - ssl
  - addon_config:rw
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface
options:
  log_level: warning
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(debug|info|warning)?
  certfile: str
  keyfile: str
  ssl: bool
  leave_front_door_open: bool?
image: "ghcr.io/yeonv/{arch}-addon-ledfx-dev"
