---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
labels:
  org.opencontainers.image.authors: "LonelyPlayer"
  org.opencontainers.image.title: "Home Assistant LedFX add-on"
  org.opencontainers.image.description: "A network based LED effect controller with support for advanced real-time audio effects!"
  org.opencontainers.image.source: "https://github.com/LonelyPlayer/home-assistant-addons/tree/master/ledfx-beta"
  org.opencontainers.image.licenses: "MIT"
#codenotary:
#  signer: spiroc@gmail.com
#  base_image: notary@home-assistant.io